第一次作业.
linjie-1/guigulive-operation pull request #125
Opened 2018-01-10 12:15 UTC by ethluz

比视频多一个设置地址的功能

2018-01-10 12:53 UTC, ethluz commented
8-陆周-第一课作业

2018-01-10 12:54 UTC, ethluz commented
8-陆周-第一课作业

2018-01-11 01:34 UTC, gillianth54 requested changes
Please make an attempt to implement updateEmployee()

2018-01-11 01:34 UTC, gillianth54 commented on 【测试】第一课作业.sol
> +    function colculateRunway() returns (uint) {
Typo in the method signature.

2018-01-13 14:09 UTC, ethluz commented
8-陆周-第二课作业提交

2018-01-15 08:40 UTC, gillianth54 requested changes
这次作业实现了所有功能，优化方法也很好。作业要求里要记录消耗的Calculate Runway消耗的Gas，可以做个实验哦，重复前五次就可以看出规律了。并且可以和其它同学的结果比较，不同的实现在Gas消耗上也不同的～

2018-01-16 15:49 UTC, ethluz commented
额..这个每次消耗都是一样的了.没优化之前,我忘了截图.那个是每次都会增加.(因为运算次数递增)
改过之后,每次都是一次运算.所以消耗gas都是一样的.
![image](https://user-images.githubusercontent.com/1680814/34997388-5efcfb52-fb17-11e7-99ca-4d27b8d4dc2e.png)

2018-01-20 07:49 UTC, ethluz reviewed
之前那个调试gas的.我就发了一个图.因为都一样.没优化之前的那个..没有截图...
在改回到优化之前的才行~..而且我知道那个是累加的.因为每多一个地址,循环就会多执行一次~

2018-01-20 07:51 UTC, ethluz commented
@gillianth54  之前那个工资总额的.调试.我在优化前没有做截图...但是我知道那个是累加的.因为没加一个address,那个循环就多执行一次.所以是按倍递增的.只是不想在改回以前的代码调试了...

2018-01-20 07:51 UTC, ethluz commented
求merge

2018-01-21 06:07 UTC, gillianth54 requested changes

2018-01-21 06:07 UTC, gillianth54 commented on Lesson3/assignment/yours.sol
> +        employees[nextAddr] = employee;
这里，var employee是一个指向employees[employeeId]的指针。把这个指针赋给新的员工就意味着新旧“两个”员工“同时指向了storage中的同一个地址。再把这个地址指向的内容删除就意味着新旧员工都失去了这个struct的内容。

2018-01-22 07:37 UTC, gillianth54 requested changes

2018-01-22 07:37 UTC, gillianth54 commented on Lesson4/assignment/test/payroll.js
> +  });
覆盖了两个最基本的单元测试，很好啊！还可以尝试测试下添加了存在的员工以及删除了不存在的员工的情况，看看能不能捕捉到异常。

2018-01-25 03:28 UTC, gillianth54 commented on Lesson3/assignment/yours.sol
> +    function changePaymentAddress(address employeeId, address nextAddr) employeeExist(employeeId) employeeExist(nextAddr) {
employeeExist(nextAddr)是在要求新地址对应员工存在，似乎要求新地址对应员工不存在比较恰当

2026-01-10 16:29 UTC, closed without merging