52-聪颖同学-lesson3
linjie-1/guigulive-operation pull request #308
Opened 2018-01-17 13:23 UTC by Congying1112

李老师🙋🙋

2018-01-18 15:00 UTC, washingweb requested changes

2018-01-18 15:00 UTC, washingweb commented on Lesson3/assignment/README.md
> + function changePaymentAddress(address oldAddr, address newAddr) onlyOwner hasEmployee(oldAddr) {
不需要两个参数，可以通过msg.sender来判断

2018-01-18 15:00 UTC, washingweb commented on Lesson3/assignment/README.md
> += [Z, K1, K2, A, B, C, O]
结果不对

注意 contract Child is Base1, Base2，在solidity中Base2比Base1优先

2018-01-20 01:09 UTC, washingweb commented on Lesson3/assignment/README.md
> + function changePaymentAddress(address oldAddr, address newAddr) onlyOwner hasEmployee(oldAddr) {
之前看错了。你这个是owner设置的做法，可以的

2018-01-20 06:07 UTC, Congying1112 commented
@washingweb

2018-01-20 06:11 UTC, washingweb approved these changes
通过！

2018-01-20 06:11 UTC, merged